// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_W3arMjkjzkuxZr8jr2U7X5jiBhsbTGE',
    appId: '1:781881112322:web:9529bfdac6d122ce21b41b',
    messagingSenderId: '781881112322',
    projectId: 'emergency-alert-d777b',
    authDomain: 'emergency-alert-d777b.firebaseapp.com',
    storageBucket: 'emergency-alert-d777b.firebasestorage.app',
    measurementId: 'G-PTPTZZZLED',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsj6Sj8DIBMhvPHPfkqGOZHWCpWvb1ZVE',
    appId: '1:781881112322:android:4e0fc5ebd665d02a21b41b',
    messagingSenderId: '781881112322',
    projectId: 'emergency-alert-d777b',
    storageBucket: 'emergency-alert-d777b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDepa897emIS3mvIrb6b9yRdvTfAg8-XUc',
    appId: '1:781881112322:ios:e7bf934a5e3a6fb521b41b',
    messagingSenderId: '781881112322',
    projectId: 'emergency-alert-d777b',
    storageBucket: 'emergency-alert-d777b.firebasestorage.app',
    iosBundleId: 'com.example.emergencyalert',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDepa897emIS3mvIrb6b9yRdvTfAg8-XUc',
    appId: '1:781881112322:ios:eb258950ab0e2f7021b41b',
    messagingSenderId: '781881112322',
    projectId: 'emergency-alert-d777b',
    storageBucket: 'emergency-alert-d777b.firebasestorage.app',
    iosBundleId: 'com.example.emergencyAlert',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_W3arMjkjzkuxZr8jr2U7X5jiBhsbTGE',
    appId: '1:781881112322:web:45e0145317ea935521b41b',
    messagingSenderId: '781881112322',
    projectId: 'emergency-alert-d777b',
    authDomain: 'emergency-alert-d777b.firebaseapp.com',
    storageBucket: 'emergency-alert-d777b.firebasestorage.app',
    measurementId: 'G-8PJYSDR2S6',
  );
}
